version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.0-apache
    ports:
      - "8080:80" # Expose port 8080 on WSL to port 80 in the container
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: prendsTaGoDb
      MYSQL_USER: PTG_user
      MYSQL_PASSWORD: PTG_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306" # Expose port 3306 on the host to port 3306 in the container

volumes:
  db_data:
